### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by wilpola** [wilpola/mock-todo#2]
## Purpose
There has to be a way to search for different todo items, and for this reason there will be a search bar at the top of the page where onChange, the page will filter all of the todo items to only display the ones that match the search results.

## Info
Author: @wilpola 
date: 2/3/23

## Tasks
- [x] Create search component
- [x] Display it at the top of the page
- [ ] Filter state based on input value
