### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by wilpola** [wilpola/mock-todo#4]
## Purpose
There needs to be an easy and accessible way to access the data, and remove the data that is stored to reset the application.
The settings page has a series of buttons that allow the user to configure the application.

## Info
Author: @wilpola 
Date: 2/4/2023

## Tasks
- [x] Create the settings page component
- [x] Create and add the Route to the component
- [x] Create buttons that configure the app
