### ISSUE TITLE
Modal for editing

### ISSUE THREAD

**Issue by wilpola** [wilpola/mock-todo#6]
## Purpose
Create a modal component that will be repurposed for creating and editing tasks in memory

## Info
Author: @wilpola 
Date: 2/4/2023

## Tasks
- [ ] Create the modal component
- [ ] Style the modal component
- [ ] Build editing modal
- [ ] Build Creation modal
